name: VampireZ
version: '${version}'
main: com.tigerhix.vampirez.Main
api-version: '1.16'
depend: []
authors: [TigerHix, Repack by pixkk]
description: Vampires and survivors. Who gonna win?
commands:
  vampire:
    description: Vampire commands.
    usage: /<command>